apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  DB_HOST: {{ .Release.Name }}-postgres
  DB_NAME: {{ .Values.postgres.database }}
  DB_USER: {{ .Values.postgres.user }}
