app:
  replicaCount: 2
  image:
    repository: flask-k8s-app
    tag: 77edd2cb
    pullPolicy: Never
  port: 5000

postgres:
  image: postgres:15
  database: mydb
  user: myuser
  password: mysecretpassword
  storage: 1Gi

service:
  type: NodePort
  port: 5000
  nodePort: 30500
