app:
  replicaCount: 1
  image:
    repository: zulfazlin/flask-k8s-app
    tag: 9d2bf312
    pullPolicy: Always
  port: 5000

postgres:
  image: postgres:15
  database: mydb_dev
  user: myuser
  password: devpassword
  storage: 500Mi

service:
  type: NodePort
  port: 5000
  nodePort: 30501
