name: CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: zulfazlin/flask-k8s-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set image tag
      id: tag
      run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./app
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.TAG }}

    - name: Update Helm values
      run: |
        sed -i "s/tag: .*/tag: ${{ steps.tag.outputs.TAG }}/" helm/flask-app/values.yaml

    - name: Commit updated values
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add helm/flask-app/values.yaml
        git commit -m "ci: update image tag to ${{ steps.tag.outputs.TAG }}"
        git push
